title: "Manual Técnico: SystemC"
logo: /assets/img/logo-systemc.png
description: Información básica para implementar SystemC en soluciones de simulación
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
baseurl: /manual-tecnico-systemc
